/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author Marcos
 */
public class TelaFatorial extends javax.swing.JFrame {

    /**
     * Creates new form TelaFatorial
     */
    public TelaFatorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        baseValor = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        resultadoFatorial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFatorial = new javax.swing.JLabel();
        numeroFatorial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculando Fatorial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baseValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        baseValor.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        baseValor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                baseValorStateChanged(evt);
            }
        });
        getContentPane().add(baseValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 78, 85, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exclamacao.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 101, 201));

        resultadoFatorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultadoFatorial.setForeground(new java.awt.Color(255, 51, 51));
        resultadoFatorial.setText("1");
        getContentPane().add(resultadoFatorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 80, 123, 47));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("! =");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 78, 33, 47));

        txtFatorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFatorial.setText("0");
        getContentPane().add(txtFatorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 390, 30));

        numeroFatorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroFatorial.setText("0!=");
        getContentPane().add(numeroFatorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baseValorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_baseValorStateChanged
        int valor = (int) baseValor.getValue();
        int resultado = valor;
        numeroFatorial.setText(valor + "!=");
        String textoFatorial = new String(valor + " x ")  ;
        while (valor > 1){
            resultado *= (--valor);
            if (valor == 1) {
                textoFatorial += valor;
            } else {
                textoFatorial += valor + " x ";
            }
        };
        resultadoFatorial.setText(Integer.toString(resultado));
        txtFatorial.setText(textoFatorial);
    }//GEN-LAST:event_baseValorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFatorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner baseValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel numeroFatorial;
    private javax.swing.JLabel resultadoFatorial;
    private javax.swing.JLabel txtFatorial;
    // End of variables declaration//GEN-END:variables
}
